from .userView import UserListaView, UserRetrieveUpdateDeleteView
from .medicoView import MedicoListCreateView, MedicoRetrieveUpdateView
from .pacienteView import PacienteListCreateView, PacienteRetrieveUpdateView
from .enfermeroView import EnfermeroListCreateView, EnfermeroRetrieveUpdateView